In [1]:
import pandas as pd
import json
import urllib.request

url = 'https://raw.githubusercontent.com/Biuni/PokemonGO-Pokedex/master/pokedex.json'

# Download the JSON file
filename, headers = urllib.request.urlretrieve(url, filename="pokedex.json")

# Read the JSON file into a Pandas DataFrame
with open(filename) as json_file:
    data = json.load(json_file)
    df = pd.DataFrame(data['pokemon'])
df.head(10)

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
0,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
1,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
2,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
3,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN
4,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
5,6,006,Charizard,http://www.serebii.net/pokemongo/pokemon/006.png,"[Fire, Flying]",1.70 m,90.5 kg,Charmander Candy,NaN,Not in Eggs,0.0031,0.31,13:34,None,"[Water, Electric, Rock]",NaN,"[{'num': '004', 'name': 'Charmander'}, {'num':..."
6,7,007,Squirtle,http://www.serebii.net/pokemongo/pokemon/007.png,[Water],0.51 m,9.0 kg,Squirtle Candy,25.0,2 km,0.5800,58.00,04:25,[2.1],"[Electric, Grass]","[{'num': '008', 'name': 'Wartortle'}, {'num': ...",NaN
7,8,008,Wartortle,http://www.serebii.net/pokemongo/pokemon/008.png,[Water],0.99 m,22.5 kg,Squirtle Candy,100.0,Not in Eggs,0.0340,3.40,07:02,[1.4],"[Electric, Grass]","[{'num': '009', 'name': 'Blastoise'}]","[{'num': '007', 'name': 'Squirtle'}]"
8,9,009,Blastoise,http://www.serebii.net/pokemongo/pokemon/009.png,[Water],1.60 m,85.5 kg,Squirtle Candy,NaN,Not in Eggs,0.0067,0.67,00:06,None,"[Electric, Grass]",NaN,"[{'num': '007', 'name': 'Squirtle'}, {'num': '..."
9,10,010,Caterpie,http://www.serebii.net/pokemongo/pokemon/010.png,[Bug],0.30 m,2.9 kg,Caterpie Candy,12.0,2 km,3.0320,303.20,16:35,[1.05],"[Fire, Flying, Rock]","[{'num': '011', 'name': 'Metapod'}, {'num': '0...",NaN

In [2]:
df.shape() #getting how many rows and coulmns are their in dataset.

(151, 17)

In [3]:
df.sample()

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
145,146,146,Moltres,http://www.serebii.net/pokemongo/pokemon/146.png,"[Fire, Flying]",2.01 m,60.0 kg,None,NaN,Not in Eggs,0.0,0.0,N/A,None,"[Water, Electric, Rock]",NaN,NaN

In [4]:
df.describe(include='all')

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
count,151.000000,151,151,151,151,151,151,151,70.000000,151,151.000000,151.000000,151,70,151,70,72
unique,NaN,151,151,151,34,26,108,56,NaN,5,NaN,NaN,126,68,33,70,70
top,NaN,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,[Water],0.99 m,30.0 kg,None,NaN,Not in Eggs,NaN,NaN,N/A,[1.79],"[Electric, Grass]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...","[{'num': '133', 'name': 'Eevee'}]"
freq,NaN,1,1,1,18,20,7,27,NaN,77,NaN,NaN,6,2,18,1,3
mean,76.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.300000,NaN,0.731985,53.992603,NaN,NaN,NaN,NaN,NaN
std,43.734045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.897512,NaN,1.956376,111.156064,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,38.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.250000,NaN,0.015500,1.450000,NaN,NaN,NaN,NaN,NaN
50%,76.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,0.074000,7.200000,NaN,NaN,NaN,NaN,NaN
75%,113.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,0.620000,55.000000,NaN,NaN,NaN,NaN,NaN
max,151.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400.000000,NaN,15.980000,712.000000,NaN,NaN,NaN,NaN,NaN

In [5]:
data_copy = df.copy() #making copy of a dataset

In [6]:
data_copy ['spawn_time'] == 'N/A'

0      False
1      False
2      False
3      False
4      False
       ...
146    False
147    False
148    False
149     True
150     True
Name: spawn_time, Length: 151, dtype: bool

In [7]:
data_copy['spawn_time'] =data_copy['spawn_time'].str.replace('N/A','00:00')

In [8]:
data_copy['spawn_time'] = data_copy['spawn_time'].apply(lambda x: '00:' + str(x)) #using lambda function to add into hours format.

In [9]:
data_copy['spawn_time']

0      00:20:00
1      00:07:00
2      00:11:30
3      00:08:45
4      00:19:00
         ...
146    00:06:41
147    00:11:57
148    00:23:38
149    00:00:00
150    00:00:00
Name: spawn_time, Length: 151, dtype: object

In [10]:
data_copy['spawn_time'] = pd.to_timedelta(data_copy['spawn_time'])  #datytime conversion

In [11]:
data_copy['spawn_time']

0     0 days 00:20:00
1     0 days 00:07:00
2     0 days 00:11:30
3     0 days 00:08:45
4     0 days 00:19:00
            ...
146   0 days 00:06:41
147   0 days 00:11:57
148   0 days 00:23:38
149   0 days 00:00:00
150   0 days 00:00:00
Name: spawn_time, Length: 151, dtype: timedelta64[ns]

In [13]:
rt = data_copy.copy()

In [14]:
rt.index = rt.index +1 #reseting the index values 
rt['next_evolutio'] = rt.apply(lambda row: [{'num': str(row['num'][0:]), 'name': row['name'][0:]}], axis=1)  #making new column which takes name and number into dict format with the help of lambda function 
rt['next_evolutio'] = rt['next_evolutio'].reset_index(drop=True)
rt

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,next_evolutio
1,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,0 days 00:20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,"[{'num': '002', 'name': 'Ivysaur'}]"
2,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,0 days 00:07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]","[{'num': '003', 'name': 'Venusaur'}]"
3,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,0 days 00:11:30,None,"[Fire, Ice, Flying, Psychic]",NaN,"[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...","[{'num': '004', 'name': 'Charmander'}]"
4,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,0 days 00:08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,"[{'num': '005', 'name': 'Charmeleon'}]"
5,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,0 days 00:19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '006', 'name': 'Charizard'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,0 days 00:06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,"[{'num': '148', 'name': 'Dragonair'}]"
148,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,0 days 00:11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]","[{'num': '149', 'name': 'Dragonite'}]"
149,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,0 days 00:23:38,None,"[Ice, Rock, Dragon, Fairy]",NaN,"[{'num': '147', 'name': 'Dratini'}, {'num': '1...","[{'num': '150', 'name': 'Mewtwo'}]"
150,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]",NaN,NaN,"[{'num': '151', 'name': 'Mew'}]"
151,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]",NaN,NaN,NaN

In [15]:
rt['next_evolution'] = rt['next_evolution'].fillna(rt['next_evolutio']) #fill new column values where the cell is empty
rt

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,next_evolutio
1,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,0 days 00:20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,"[{'num': '002', 'name': 'Ivysaur'}]"
2,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,0 days 00:07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]","[{'num': '003', 'name': 'Venusaur'}]"
3,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,0 days 00:11:30,None,"[Fire, Ice, Flying, Psychic]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...","[{'num': '004', 'name': 'Charmander'}]"
4,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,0 days 00:08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,"[{'num': '005', 'name': 'Charmeleon'}]"
5,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,0 days 00:19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '006', 'name': 'Charizard'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,0 days 00:06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,"[{'num': '148', 'name': 'Dragonair'}]"
148,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,0 days 00:11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]","[{'num': '149', 'name': 'Dragonite'}]"
149,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,0 days 00:23:38,None,"[Ice, Rock, Dragon, Fairy]","[{'num': '150', 'name': 'Mewtwo'}]","[{'num': '147', 'name': 'Dratini'}, {'num': '1...","[{'num': '150', 'name': 'Mewtwo'}]"
150,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]","[{'num': '151', 'name': 'Mew'}]",NaN,"[{'num': '151', 'name': 'Mew'}]"
151,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]",NaN,NaN,NaN

In [18]:
rt.index = rt.index -1
rt['prev_evolutio'] = rt.apply(lambda row: [{'num': str(row['num'][0:]), 'name': row['name'][0:]}], axis=1) #making new column which takes name and number into dict format with the help of lambda function 
rt['prev_evolutio'] = rt['prev_evolutio'].reset_index(drop=True)
 
rt

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,next_evolutio,prev_evolutio
-1,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,0 days 00:20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,"[{'num': '002', 'name': 'Ivysaur'}]",NaN
0,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,0 days 00:07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
1,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,0 days 00:11:30,None,"[Fire, Ice, Flying, Psychic]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...","[{'num': '004', 'name': 'Charmander'}]","[{'num': '002', 'name': 'Ivysaur'}]"
2,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,0 days 00:08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...",NaN,"[{'num': '005', 'name': 'Charmeleon'}]","[{'num': '003', 'name': 'Venusaur'}]"
3,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,0 days 00:19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,0 days 00:06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...",NaN,"[{'num': '148', 'name': 'Dragonair'}]","[{'num': '146', 'name': 'Moltres'}]"
146,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,0 days 00:11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
147,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,0 days 00:23:38,None,"[Ice, Rock, Dragon, Fairy]","[{'num': '150', 'name': 'Mewtwo'}]","[{'num': '147', 'name': 'Dratini'}, {'num': '1...","[{'num': '150', 'name': 'Mewtwo'}]","[{'num': '148', 'name': 'Dragonair'}]"
148,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]","[{'num': '151', 'name': 'Mew'}]",NaN,"[{'num': '151', 'name': 'Mew'}]","[{'num': '149', 'name': 'Dragonite'}]"
149,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]",NaN,NaN,NaN,"[{'num': '150', 'name': 'Mewtwo'}]"

In [19]:
rt['prev_evolution'] = rt['prev_evolution'].fillna(rt['prev_evolutio']) #fill new column values where the cell is empty in a coulmn row
rt

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution,next_evolutio,prev_evolutio
-1,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,0 days 00:20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN,"[{'num': '002', 'name': 'Ivysaur'}]",NaN
0,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,0 days 00:07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
1,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,0 days 00:11:30,None,"[Fire, Ice, Flying, Psychic]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '001', 'name': 'Bulbasaur'}, {'num': ...","[{'num': '004', 'name': 'Charmander'}]","[{'num': '002', 'name': 'Ivysaur'}]"
2,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,0 days 00:08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '005', 'name': 'Charmeleon'}]","[{'num': '003', 'name': 'Venusaur'}]"
3,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,0 days 00:19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,0 days 00:06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...","[{'num': '146', 'name': 'Moltres'}]","[{'num': '148', 'name': 'Dragonair'}]","[{'num': '146', 'name': 'Moltres'}]"
146,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,0 days 00:11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
147,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,0 days 00:23:38,None,"[Ice, Rock, Dragon, Fairy]","[{'num': '150', 'name': 'Mewtwo'}]","[{'num': '147', 'name': 'Dratini'}, {'num': '1...","[{'num': '150', 'name': 'Mewtwo'}]","[{'num': '148', 'name': 'Dragonair'}]"
148,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]","[{'num': '151', 'name': 'Mew'}]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '151', 'name': 'Mew'}]","[{'num': '149', 'name': 'Dragonite'}]"
149,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]",NaN,"[{'num': '150', 'name': 'Mewtwo'}]",NaN,"[{'num': '150', 'name': 'Mewtwo'}]"

In [20]:
rt.drop(['next_evolutio','prev_evolutio'], axis=1) #droping the unwante column

,id,num,name,img,type,height,weight,candy,candy_count,egg,spawn_chance,avg_spawns,spawn_time,multipliers,weaknesses,next_evolution,prev_evolution
-1,1,001,Bulbasaur,http://www.serebii.net/pokemongo/pokemon/001.png,"[Grass, Poison]",0.71 m,6.9 kg,Bulbasaur Candy,25.0,2 km,0.6900,69.00,0 days 00:20:00,[1.58],"[Fire, Ice, Flying, Psychic]","[{'num': '002', 'name': 'Ivysaur'}, {'num': '0...",NaN
0,2,002,Ivysaur,http://www.serebii.net/pokemongo/pokemon/002.png,"[Grass, Poison]",0.99 m,13.0 kg,Bulbasaur Candy,100.0,Not in Eggs,0.0420,4.20,0 days 00:07:00,"[1.2, 1.6]","[Fire, Ice, Flying, Psychic]","[{'num': '003', 'name': 'Venusaur'}]","[{'num': '001', 'name': 'Bulbasaur'}]"
1,3,003,Venusaur,http://www.serebii.net/pokemongo/pokemon/003.png,"[Grass, Poison]",2.01 m,100.0 kg,Bulbasaur Candy,NaN,Not in Eggs,0.0170,1.70,0 days 00:11:30,None,"[Fire, Ice, Flying, Psychic]","[{'num': '004', 'name': 'Charmander'}]","[{'num': '001', 'name': 'Bulbasaur'}, {'num': ..."
2,4,004,Charmander,http://www.serebii.net/pokemongo/pokemon/004.png,[Fire],0.61 m,8.5 kg,Charmander Candy,25.0,2 km,0.2530,25.30,0 days 00:08:45,[1.65],"[Water, Ground, Rock]","[{'num': '005', 'name': 'Charmeleon'}, {'num':...","[{'num': '003', 'name': 'Venusaur'}]"
3,5,005,Charmeleon,http://www.serebii.net/pokemongo/pokemon/005.png,[Fire],1.09 m,19.0 kg,Charmander Candy,100.0,Not in Eggs,0.0120,1.20,0 days 00:19:00,[1.79],"[Water, Ground, Rock]","[{'num': '006', 'name': 'Charizard'}]","[{'num': '004', 'name': 'Charmander'}]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,147,147,Dratini,http://www.serebii.net/pokemongo/pokemon/147.png,[Dragon],1.80 m,3.3 kg,Dratini Candy,25.0,10 km,0.3000,30.00,0 days 00:06:41,"[1.83, 1.84]","[Ice, Dragon, Fairy]","[{'num': '148', 'name': 'Dragonair'}, {'num': ...","[{'num': '146', 'name': 'Moltres'}]"
146,148,148,Dragonair,http://www.serebii.net/pokemongo/pokemon/148.png,[Dragon],3.99 m,16.5 kg,Dratini Candy,100.0,Not in Eggs,0.0200,2.00,0 days 00:11:57,[2.05],"[Ice, Dragon, Fairy]","[{'num': '149', 'name': 'Dragonite'}]","[{'num': '147', 'name': 'Dratini'}]"
147,149,149,Dragonite,http://www.serebii.net/pokemongo/pokemon/149.png,"[Dragon, Flying]",2.21 m,210.0 kg,Dratini Candy,NaN,Not in Eggs,0.0011,0.11,0 days 00:23:38,None,"[Ice, Rock, Dragon, Fairy]","[{'num': '150', 'name': 'Mewtwo'}]","[{'num': '147', 'name': 'Dratini'}, {'num': '1..."
148,150,150,Mewtwo,http://www.serebii.net/pokemongo/pokemon/150.png,[Psychic],2.01 m,122.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]","[{'num': '151', 'name': 'Mew'}]","[{'num': '149', 'name': 'Dragonite'}]"
149,151,151,Mew,http://www.serebii.net/pokemongo/pokemon/151.png,[Psychic],0.41 m,4.0 kg,None,NaN,Not in Eggs,0.0000,0.00,0 days 00:00:00,None,"[Bug, Ghost, Dark]",NaN,"[{'num': '150', 'name': 'Mewtwo'}]"

In [21]:
rt.to_csv('final.csv') #saving it to CSV file